name: Build and Release

on:
  release:
    types: [created]
  push:

build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Create zip file
        run: |
          $outputPath = "${{ github.workspace }}\rust-bleh.zip"
          Compress-Archive -Path "${{ github.workspace }}\target\release\rust-bleh.exe" -DestinationPath grout-wm.zip
        shell: pwsh
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: "${{ github.workspace }}/rust-bleh.zip"